version: '3.8'

services:
  database:
    container_name: vnmzkknf-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - '33306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: vnmzkknf-app
    environment:
      - TZ=Europe/Zurich
    build:
      context: ./php
    ports:
      - '19000:9000'
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
  nginx:
    container_name: vnmzkknf-nginx
    image: nginx:stable-alpine
    ports:
      - '18080:80'
    volumes:
      - ../apqu-frontend/build:/var/www/app/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
